# Generated by Django 5.0 on 2023-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
