# Generated by Django 4.2.9 on 2024-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_observation_genotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
