# Generated by Django 4.2.9 on 2024-01-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_sample_collection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='observation_date',
        ),
    ]
