# Generated by Django 4.2.9 on 2024-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_observation_observation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(default='2024-03-03'),
            preserve_default=False,
        ),
    ]
