# Generated by Django 4.2.9 on 2024-01-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_observation_observation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='genotype',
            new_name='replicate',
        ),
    ]
