# Generated by Django 4.2.9 on 2024-02-06 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_usercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='country',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='project',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='species',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='biosamples',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='fragment',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='biosample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.biosample'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biosample',
            name='colony',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biosamples', to='projects.colony'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercart',
            name='items',
            field=models.ManyToManyField(to='projects.colony'),
        ),
    ]
