# Generated by Django 4.2.9 on 2024-02-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_experiment_date_experiment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='name',
        ),
    ]
