# Generated by Django 4.2.9 on 2024-02-06 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_biosample_collection_date_biosample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='project',
        ),
        migrations.AddField(
            model_name='publication',
            name='observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.observation'),
            preserve_default=False,
        ),
    ]
