# Generated by Django 4.2.9 on 2024-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_publication_project_publication_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='observation',
        ),
        migrations.AddField(
            model_name='observation',
            name='publications',
            field=models.ManyToManyField(related_name='associated_observations', to='projects.publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='observations',
            field=models.ManyToManyField(related_name='associated_publications', to='projects.observation'),
        ),
    ]
