# Generated by Django 4.2.9 on 2024-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_observation_experiment_alter_observation_biosample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='projects',
            field=models.ManyToManyField(related_name='project_publications', to='projects.project'),
        ),
    ]
