# Generated by Django 4.2.9 on 2024-02-07 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0027_remove_publication_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='items',
        ),
        migrations.AddField(
            model_name='biosample',
            name='publication',
            field=models.ManyToManyField(related_name='biosamples', to='projects.publication'),
        ),
        migrations.AddField(
            model_name='colony',
            name='in_carts',
            field=models.ManyToManyField(related_name='colonies', to='projects.usercart'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='biosample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.biosample'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.experiment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='projects',
            field=models.ManyToManyField(related_name='publications', to='projects.project'),
        ),
    ]
