# Generated by Django 4.2.9 on 2024-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_rename_publication_biosample_publications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='ed50_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pam_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
