# Generated by Django 4.2.9 on 2024-02-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_colony_ed50_value_alter_observation_pam_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='publications',
            field=models.ManyToManyField(related_name='projects', to='projects.publication'),
        ),
    ]
