# Generated by Django 4.2.9 on 2024-02-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_publication_projects_project_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='publications',
        ),
        migrations.AddField(
            model_name='publication',
            name='biosamples',
            field=models.ManyToManyField(related_name='publications', to='projects.biosample'),
        ),
    ]
