# Generated by Django 4.2.9 on 2024-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_remove_biosample_publications_publication_biosamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='projects',
            field=models.ManyToManyField(related_name='biosamples', to='projects.project'),
        ),
    ]
