# Generated by Django 4.2.9 on 2024-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_remove_biosample_projects_project_biosamples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='carts',
        ),
        migrations.AddField(
            model_name='usercart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='projects.colony'),
        ),
    ]
