# Generated by Django 4.2.9 on 2024-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_remove_colony_carts_usercart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='_sst_clim_mmm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colony',
            name='thermal_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
