# Generated by Django 4.2.9 on 2024-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_colony__sst_clim_mmm_remove_colony_ed50_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermaltolerance',
            name='abs_thermal_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thermaltolerance',
            name='rel_thermal_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
